apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::815407921825:role/eksctl-eksctl-demo-nodegroup-ng-8a-NodeInstanceRole-OzOBTs1fgQYd
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::815407921825:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-05-05T16:09:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1340"
  uid: 96baaf5f-b98d-4304-a282-4eabde9dd988
